#!/bin/bash


## CONFIG
init_delay=10          # The starting retry delay (in seconds.)
max_delay=$((60*10))   # The maximum amount of time to delay beteween checking for a live stream.
delay="${init_delay}"  # Ongoing delay counter. Doubles itself if there is no live stream.


## VARIABLES
bindir="$(dirname "$(readlink -fm "$0")")"
name="${1}"
url="$(cat ${bindir}/voddo.json | jq --arg name "${name}" '.[] | select(.name==$name).url' | tr -d \")" # get the url from ref.json


## FUNCTIONS
ekko () {
  echo "[$(date)] - ${1}"
}

init () {
  if [ -z ${name} ]; then
    ekko "First parameter must be a stream name. See ref.json for example."
    exit 5
  fi

  if [ -z ${url} ]; then
    ekko "Could not find a matching url given name, \"${name}\". Ensure that the name/url pair exists in ref.json"
    exit 6
  fi

  ekko "Attempting to download ${name}'s stream at URL ${url}... Press Ctrl+C to quit."
}


main () {
  while :; do

    # Attempt to download the stream.
    # We use the name parameter sent to this script to look up the stream url in `ref.json`.
    youtube-dl -f best "${url}"

    # Reset the delay time if youtube-dl exited with 0 error code
    # This would suggest that the streamer ended their stream.
    # In the case that the stream ending was temporary (so the streamer could fix a technical problem),
    # we want youtube-dl to resume quickly afterwards to catch the stream as it continues.
    if [[ $? -eq 0 ]]; then let delay=init_delay; fi

    # Slowly increase the delay time between retries.
    # This is done to be polite to the streaming platform.
    # We wait longer and longer between tries, eventually maxing out at ${max_delay} seconds
    if [[ delay -ge max_delay ]]; then let delay=max_delay
      else let delay=delay*2
    fi

    ekko "sleeping for ${delay} seconds"
    sleep "${delay}"

  done
}


init
main
